site_name: RLCMS Documentation

nav:
    - Overview: index.md

theme: 
    name: material
    favicon: 'img/RLCMS-LOGO-icon.png'
    logo: 'img/RLCMS-LOGO-CIRCLE-COLOR.png'

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - markdown.extensions.codehilite:
        guess_lang: false
